### ISSUE TITLE
eicSimuBeamEffects Wont Compile in eic-shell version > 26.04.1-stable

### ISSUE THREAD

**Issue by bspage912** [bspage912/eicSimuBeamEffects#10]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released):
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Clone main branch of eicSimuBeamEffects
2. Run eic-shell, either nightly version or any stable version later than 26.04.1
3. From Pythia8 dir, run "cmake -S . -B build" and "cmake --build build"

### Expected Result: (what do you expect when you execute the steps above)

Should compile without error.
Note: This software does compile in eic-shell version 26.04.1-stable and 26.04.0-stable (haven't checked earlier)

### Actual Result: (what do you get when you execute the steps above)

jug_dev+> bpage@eicsub01:~/EPIC/officialSimu/pythia8/dis/newTest/eicSimuBeamEffects/Pythia8$ cmake --build build
[ 16%] Building CXX object CMakeFiles/eicBeamShape.dir/eicBeamShape.cxx.o
[ 33%] Linking CXX static library /eic/u/bpage/EPIC/officialSimu/pythia8/dis/newTest/eicSimuBeamEffects/Pythia8/lib/libeicBeamShape.a
[ 33%] Built target eicBeamShape
[ 50%] Building CXX object CMakeFiles/runBeamShape.dir/PythiaBeamShape.cxx.o
[ 66%] Linking CXX executable /eic/u/bpage/EPIC/officialSimu/pythia8/dis/newTest/eicSimuBeamEffects/Pythia8/bin/runBeamShape
[ 66%] Built target runBeamShape
[ 83%] Building CXX object CMakeFiles/runBeamShapeHepMC.dir/PythiaBeamShapeHepMC.cxx.o
/eic/u/bpage/EPIC/officialSimu/pythia8/dis/newTest/eicSimuBeamEffects/Pythia8/PythiaBeamShapeHepMC.cxx:4:10: fatal error: 'Pythia8/Pythia.h' file not found
    4 | #include "Pythia8/Pythia.h"
      |          ^~~~~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [CMakeFiles/runBeamShapeHepMC.dir/build.make:79: CMakeFiles/runBeamShapeHepMC.dir/PythiaBeamShapeHepMC.cxx.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:157: CMakeFiles/runBeamShapeHepMC.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by veprbl** [comment]
Thanks for detailed report. This should be fixed in https://github.com/eic/eicSimuBeamEffects/commit/98b1d6d9f85e9696403488f11d6b11af87cd053d

**Comment by bspage912** [comment]
I confirm that the code now compiles - thanks!
